M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-10-13T22:34:14+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-13T22:34:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X1.4323Y-1.6917
X1.4323Y-1.9193
M30
